### ISSUE TITLE
Load server project at startup prevents sbt clean

### ISSUE THREAD

**Issue by marcgrue** [vmunier/play-scalajs.g8#111]
Setting

    onLoad in Global := (onLoad in Global).value.andThen(state => "project server" :: state)
    // or
    Global / onLoad := (Global / onLoad).value.andThen(state => "project server" :: state)

in the build file prevents `sbt clean` from cleaning. 

This bite me when I couldn't get rid of generated source files with a `sbt clean compile` and it wasn't obvious that this was the culprit. Maybe loading the server can be done in another way? Or it would be nice to mention this issue in the Readme.

**Comment by vmunier** [comment]
When loading the `server` project at SBT startup, calling `clean` will only delete the server's generated files (in the `server/target` directory). You need to call `root/clean` to delete the generated files for all the projects. I've opened a PR to update the README.
