### ISSUE TITLE
Add example showing how to include js dependencies using findScript

### ISSUE THREAD

**Issue by abrighton** [vmunier/play-scalajs.g8#126]
It took me a while to figure out the right way to get the js dependencies for a Play/Scalajs app.
I found that the client needed these lines in buid.sbt:

```
    Compile / fastLinkJS / jsMappings += toPathMapping((Compile / packageJSDependencies).value),
    Compile / fullLinkJS / jsMappings += toPathMapping((Compile / packageMinifiedJSDependencies).value),
```
I also changed findScript.scala.html:

```
@(assets: AssetsFinder, scripts: String*)

@scripts.find(name => getClass.getResource(s"/public/$name") != null).map { asset =>
  <script src=@assets.path(asset) type="text/javascript"></script>
}
```

which may not be necessary, and added this to main.scala.html:
```
        @findScript(assets, "client-jsdeps.js", "client-jsdeps.min.js")
```
Without the above line, the js dependencies were not included.
It would be helpful to include this in the template.

For reference, the branch for the project I tested this with is [here](https://github.com/tmtsoftware/icd/tree/ICDDB-120-open-api-support-upgrade-deps).

**Comment by vmunier** [comment]
I have reintroduced scalajs-scripts. `v1.2.0` has just been published, which supports sbt-web-scalajs `v1.2.0`, i.e. it includes the `<project>-<fastopt|opt>/main.js` file. As before, scalajs-scripts also includes the `jsdeps` files.
