### ISSUE TITLE
crtl+d not working when trying to close local server

### ISSUE THREAD

**Issue by khanr1** [vmunier/play-scalajs.g8#138]
Hi,

I have not been able to use the `crtl+d `shortcut to stop the server as I can normally do with a normal play  application after using the command `run` or `~run`

Please let me know if I should give more details.

Thank you for the help. 

Raphael

**Comment by btskyy** [comment]
Same issue here. Just adding details. Will amend if I find anything useful.

sbt: 1.6.1
java: 11 and 17
scala: 2.13.7
os: windows and osx silicon

**Comment by btskyy** [comment]
upgrading to play 2.8.12 resolves this issue ✅

**Comment by vmunier** [comment]
> upgrading to play >= 2.8.12 resolves this issue ✅
