### ISSUE TITLE
Scala version is outdated, incompatible

### ISSUE THREAD

**Issue by SethTisue** [vmunier/play-scalajs.g8#189]
This template currently uses Scala 2.13.5, which is now quite old and does not work on modern JVMs (as per https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html).

A user was bitten by this today at https://github.com/sbt/sbt/issues/7131#issuecomment-1910497136

**Comment by vmunier** [comment]
Thanks! Fixed by https://github.com/vmunier/play-scalajs.g8/pull/190
