### ISSUE TITLE
Create Giter8 template

### ISSUE THREAD

**Issue by Grogs** [vmunier/play-scalajs.g8#51]
I've used this example as a seed for new projects a few times now - I assume this is the intended purpose 🤐 .

Given that [Lightbend's Activator is on the way out, in favour of `sbt new`](https://www.lightbend.com/blog/introducing-a-new-way-to-get-started-with-lightbend-technologies-and-saying-goodbye-to-activator)...

It would be great to make getting started with Play and Scala.js consistent with creating a plain Play Scala project, e.g. `sbt new vmunier/play-with-scalajs-seed.g8`. It should be quite straightforward to [change this repo into a giter8 template](http://www.foundweekends.org/giter8/template.html).

Thoughts?

**Comment by vmunier** [comment]
Hi,
I have changed the repository to be a Giter8 template. `sbt new vmunier/play-scalajs.g8` can be used to bootstrap a simple application with Play and Scala.js.
