### ISSUE TITLE
Reload doesn't work with flat directory structure in client/

### ISSUE THREAD

**Issue by bmccutchon** [vmunier/play-scalajs.g8#52]
To reproduce:

1) Download the project.
1) `mv client/src/main/scala/example/ScalaJSExample.scala client/` (This is totally valid in sbt!)
2) `rm -r client/src/`
3) `sbt run`
4) Open `localhost:9000`. Looks good, right? FastOpJS runs fine.
5) Modify the message in `client/src`.
6) Reload the page.

Expected behavior: It should recompile the Scala.js code and show the new message.

Actual behavior: It shows the old message and doesn't bother to recompile.

**Comment by vmunier** [comment]
Hi,

The Play Framework monitors files that are in `unmanagedSourceDirectories` and `unmanagedResourceDirectories`: https://github.com/playframework/playframework/blob/38abd1ca6d17237950c82b1483057c5c39929cb4/framework/src/sbt-plugin/src/main/scala/play/sbt/PlayCommands.scala#L95-L97 - The project's base directory is not included.

Even though it is valid to have Scala files under the project itself (e.g. under `server` or `client`), Play will not watch for any changes in these files.
