### ISSUE TITLE
sbt 1.0.2 not compatible with this example

### ISSUE THREAD

**Issue by gilbertbigras** [vmunier/play-scalajs.g8#55]
Hi Vincent

First thanks for promoting usage of scala.js with Play framework

I tried this example with the new SBT 1.0.2 and scala 2.12.3 with the most recent scala-ide 4.7.0
I modified the version numbers in build.sbt and build.properties.

Apparently SBT 1.0.2 has issues with some commands as reported here: 

build.sbt:35: error: value process is not a member of object sbt.Command
onLoad in Global := (Command.process("project server", _: State)) compose (onLoad in Global).value

Thanks

**Comment by vmunier** [comment]
Hi,
SBT 1.x has changed the Command API. When using SBT `v1.0.2`, you need to replace the `onLoad in Global` line with: `onLoad in Global := (onLoad in Global).value andThen {s: State => "project server" :: s}`.

**Comment by vmunier** [comment]
I have updated the Giter8 template to use SBT `v1.0.2`. Commit: https://github.com/vmunier/play-scalajs.g8/commit/07052a06b06455db444462814d754b7c9c8550f0.
