### ISSUE TITLE
Unable to delete file .gitignore while installing the project

### ISSUE THREAD

**Issue by OndrejSpanel** [vmunier/play-scalajs.g8#63]
When I try installing the project from the command line by typing `sbt new vmunier/play-scalajs.g8`, I get following error:

[error] java.io.IOException: Unable to delete file: D:\Users\xxxx\AppData\Local\Temp\giter8-12821319927662\src\main\g8\.gitignore

I have confirmed the file exists and my user account has full access rights to it. I was able to delete it from the explorer without any issues.

The project seems to be create fine.

This is on Windows 10 x64 pro. I have git command line and TortoiseGit installed on my machine.

**Comment by vmunier** [comment]
It seems to be a problem with `sbt new` on Windows. Similar issues in other g8 templates:
https://github.com/playframework/play-scala-seed.g8/issues/56
https://github.com/foundweekends/giter8/issues/439
