### ISSUE TITLE
"Run the application" from README.md does not work

### ISSUE THREAD

**Issue by robertPiro** [vmunier/play-scalajs.g8#64]
[server] $ open http://localhost:9000
[error] Expected ID character
[error] Not a valid command: open (similar: append, completions, loadp)
[error] Expected project ID
[error] Expected configuration
[error] Expected ':'
[error] Expected key
[error] Not a valid key: open (similar: compile, clean, ps)
[error] open http://localhost:9000
[error]     ^

**Comment by vmunier** [comment]
Hi @robertPiro,
You are not supposed to run this command inside SBT, `open http://localhost:9000` just means open http://localhost:9000 in a web browser.
